name: Generate Snake Animation

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: Platane/snk/svg-only@v3
        with:
          github_user_name: AshThe25
          outputs: |
            dist/github-contribution-grid-snake.svg?color_snake=000000&color_dots=ebedf0,c9ccd1,9aa0a6,54595e,000000
            dist/github-contribution-grid-snake-dark.svg?color_snake=ffffff&color_dots=1c1f24,3a3f47,6e7681,b1bac4,ffffff

      - uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
